# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_0_2/design_1_AXI4Stream_UART_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_UART_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SDF_Top_0_0/design_1_SDF_Top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_SDF_Top_0_0 || ORIG_REF_NAME==design_1_SDF_Top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_Input_Interface_0_0/design_1_AXI_Input_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI_Input_Interface_0_0 || ORIG_REF_NAME==design_1_AXI_Input_Interface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_Output_Interface_0_0/design_1_AXI_Output_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI_Output_Interface_0_0 || ORIG_REF_NAME==design_1_AXI_Output_Interface_0_0} -quiet] -quiet

# XDC: c:/Github/FFFT/SDF_proj_v2.xpr/SDF_proj_v2/SDF_proj_v2.gen/sources_1/bd/design_1/design_1_ooc.xdc
