# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Test_Xilinx/Test_Xilinx.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_Xilinx || ORIG_REF_NAME==Test_Xilinx} -quiet] -quiet

# IP: bd/Test_Xilinx/ip/Test_Xilinx_xfft_0_0/Test_Xilinx_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_Xilinx_xfft_0_0 || ORIG_REF_NAME==Test_Xilinx_xfft_0_0} -quiet] -quiet

# IP: bd/Test_Xilinx/ip/Test_Xilinx_clk_wiz_0_0/Test_Xilinx_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_Xilinx_clk_wiz_0_0 || ORIG_REF_NAME==Test_Xilinx_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Github/FFFT/FFT_Xilinx/FFT_Xilinx.gen/sources_1/bd/Test_Xilinx/Test_Xilinx_ooc.xdc
